name: builds

on: [workflow_dispatch, push]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Build
        run: cargo build --examples --bins --target ${{ matrix.target }} --release
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-${{ matrix.target }}
          path: target/${{ matrix.target }}/release
