name: builds

on: [workflow_dispatch, push]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-unknown-windows-msvc
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Build Linux
        run: cargo build --target ${{ matrix.target }} --release
      - name: List Files
        run: ls -lA
